// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvhpgvWtxSzQJ-BvzjbpF2USHrVmC_RJI',
    appId: '1:35690579643:web:22d0a2797fc4f4b1fd0b9e',
    messagingSenderId: '35690579643',
    projectId: 'insta-app-697f5',
    authDomain: 'insta-app-697f5.firebaseapp.com',
    storageBucket: 'insta-app-697f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3NVhF9mw-91R6ZDIQuUl3oDCSxKMWsg',
    appId: '1:35690579643:android:cfc72c587994785efd0b9e',
    messagingSenderId: '35690579643',
    projectId: 'insta-app-697f5',
    storageBucket: 'insta-app-697f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6IKdk89_LikndaHjFrW-ohUaaZPnMB8g',
    appId: '1:35690579643:ios:b4f0e7cfae5d2a55fd0b9e',
    messagingSenderId: '35690579643',
    projectId: 'insta-app-697f5',
    storageBucket: 'insta-app-697f5.appspot.com',
    iosBundleId: 'com.example.flutterInsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6IKdk89_LikndaHjFrW-ohUaaZPnMB8g',
    appId: '1:35690579643:ios:197c2347a8452584fd0b9e',
    messagingSenderId: '35690579643',
    projectId: 'insta-app-697f5',
    storageBucket: 'insta-app-697f5.appspot.com',
    iosBundleId: 'com.example.flutterInsta.RunnerTests',
  );
}
